import Foundation

/// Stable product analytics event names emitted by the macOS app.
struct MacAnalyticsEvent: RawRepresentable, Hashable, Sendable {
    let rawValue: String

    init(rawValue: String) {
        self.rawValue = rawValue
    }

    static let actionPerformed = MacAnalyticsEvent(rawValue: "mac_action_performed")
    static let buttonClicked = MacAnalyticsEvent(rawValue: "mac_button_clicked")
    static let commandPaletteCommandPerformed = MacAnalyticsEvent(rawValue: "mac_command_palette_command_performed")
    static let keyboardShortcutPerformed = MacAnalyticsEvent(rawValue: "mac_keyboard_shortcut_performed")
    static let menuActionPerformed = MacAnalyticsEvent(rawValue: "mac_menu_action_performed")
    static let contextMenuActionPerformed = MacAnalyticsEvent(rawValue: "mac_context_menu_action_performed")
    static let socketCommandPerformed = MacAnalyticsEvent(rawValue: "mac_socket_command_performed")
    static let notificationShown = MacAnalyticsEvent(rawValue: "mac_notification_shown")
    static let errorNotificationShown = MacAnalyticsEvent(rawValue: "mac_error_notification_shown")
    static let modalAlertShown = MacAnalyticsEvent(rawValue: "mac_modal_alert_shown")
    static let errorCaptured = MacAnalyticsEvent(rawValue: "mac_error_captured")
    static let uiInteraction = MacAnalyticsEvent(rawValue: "coterm_ui_interaction")
    static let collaborationShareInitiated = MacAnalyticsEvent(rawValue: "mac_collaboration_share_initiated")
    static let collaborationSessionCreated = MacAnalyticsEvent(rawValue: "mac_collaboration_session_created")
    static let collaborationSessionJoined = MacAnalyticsEvent(rawValue: "mac_collaboration_session_joined")
    static let collaborationTerminalShared = MacAnalyticsEvent(rawValue: "mac_collaboration_terminal_shared")
    static let collaborationDocumentShared = MacAnalyticsEvent(rawValue: "mac_collaboration_document_shared")
    static let collaborationInviteCodeCopied = MacAnalyticsEvent(rawValue: "mac_collaboration_invite_code_copied")
    static let collaborationRecipientsUpdated = MacAnalyticsEvent(rawValue: "mac_collaboration_recipients_updated")
    static let collaborationShareStopped = MacAnalyticsEvent(rawValue: "mac_collaboration_share_stopped")
    static let collaborationSessionLeft = MacAnalyticsEvent(rawValue: "mac_collaboration_session_left")
    static let collaborationSessionDurationRecorded = MacAnalyticsEvent(rawValue: "mac_collaboration_session_duration_recorded")
    static let collaborationInviteCodeCreated = MacAnalyticsEvent(rawValue: "mac_collaboration_invite_code_created")
    static let collaborationParticipantJoined = MacAnalyticsEvent(rawValue: "mac_collaboration_participant_joined")
    static let collaborationParticipantLeft = MacAnalyticsEvent(rawValue: "mac_collaboration_participant_left")
    static let collaborationConnectionFailed = MacAnalyticsEvent(rawValue: "mac_collaboration_connection_failed")
    static let collaborationLayoutSnapshotRecorded = MacAnalyticsEvent(rawValue: "mac_collaboration_layout_snapshot_recorded")
    static let collaborationLayoutChanged = MacAnalyticsEvent(rawValue: "mac_collaboration_layout_changed")
    static let linkingStarted = MacAnalyticsEvent(rawValue: "mac_linking_started")
    static let linkingCompleted = MacAnalyticsEvent(rawValue: "mac_linking_completed")
    static let linkingFailed = MacAnalyticsEvent(rawValue: "mac_linking_failed")
    static let workspaceCreated = MacAnalyticsEvent(rawValue: "mac_workspace_created")
    static let workspaceSelected = MacAnalyticsEvent(rawValue: "mac_workspace_selected")
    static let workspaceClosed = MacAnalyticsEvent(rawValue: "mac_workspace_closed")
    static let workspaceMoved = MacAnalyticsEvent(rawValue: "mac_workspace_moved")
    static let workspaceReordered = MacAnalyticsEvent(rawValue: "mac_workspace_reordered")
    static let workspaceLayoutSnapshotRecorded = MacAnalyticsEvent(rawValue: "mac_workspace_layout_snapshot_recorded")
    static let workspaceGroupCreated = MacAnalyticsEvent(rawValue: "mac_workspace_group_created")
    static let workspaceGroupWorkspaceAdded = MacAnalyticsEvent(rawValue: "mac_workspace_group_workspace_added")
    static let workspaceGroupWorkspaceRemoved = MacAnalyticsEvent(rawValue: "mac_workspace_group_workspace_removed")
    static let windowCreated = MacAnalyticsEvent(rawValue: "mac_window_created")
    static let windowFocused = MacAnalyticsEvent(rawValue: "mac_window_focused")
    static let windowClosed = MacAnalyticsEvent(rawValue: "mac_window_closed")
    static let workspaceWindowMoved = MacAnalyticsEvent(rawValue: "mac_workspace_window_moved")
    static let surfaceCreated = MacAnalyticsEvent(rawValue: "mac_surface_created")
    static let surfaceClosed = MacAnalyticsEvent(rawValue: "mac_surface_closed")
    static let surfaceSelected = MacAnalyticsEvent(rawValue: "mac_surface_selected")
    static let surfaceSplitCreated = MacAnalyticsEvent(rawValue: "mac_surface_split_created")
    static let browserOpened = MacAnalyticsEvent(rawValue: "mac_browser_opened")
    static let browserButtonClicked = MacAnalyticsEvent(rawValue: "mac_browser_button_clicked")
    static let browserTabCreated = MacAnalyticsEvent(rawValue: "mac_browser_tab_created")
    static let browserSplitCreated = MacAnalyticsEvent(rawValue: "mac_browser_split_created")
    static let terminalCreated = MacAnalyticsEvent(rawValue: "mac_terminal_created")
    static let terminalSplitCreated = MacAnalyticsEvent(rawValue: "mac_terminal_split_created")
}
