#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
AUTH_MODE="hmac"
RUN_SMOKE="0"
PRINT_CONFIG="0"
CONFIG_FILE="$ROOT/.coterm-self-host.env"
CONTEXT_FILE="$ROOT/.coterm-self-host.context.json"
GENERATED_SECRET=""

usage() {
  cat <<'USAGE'
Usage: bun run deploy:self-host [--auth hmac|noauth] [--smoke] [--print-config]

Deploy the Coterm self-hosted collaboration backend to Cloudflare Workers.

Default:
  --auth hmac     Generate one shared COLLAB_AUTH_SECRET and install it on all workers.

Options:
  --auth noauth   Local testing only. Relay still requires control-plane grants,
                  but grants are unsigned and not a security boundary.
  --smoke         Run the live end-to-end smoke test after health checks.
  --print-config  Print the last saved client configuration and exit.
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --auth)
      AUTH_MODE="${2:-}"
      shift 2
      ;;
    --smoke)
      RUN_SMOKE="1"
      shift
      ;;
    --print-config)
      PRINT_CONFIG="1"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [ "$AUTH_MODE" != "noauth" ] && [ "$AUTH_MODE" != "hmac" ]; then
  echo "--auth must be noauth or hmac" >&2
  exit 1
fi

need_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing required command: $1" >&2
    exit 1
  fi
}

print_saved_config() {
  if [ ! -f "$CONFIG_FILE" ]; then
    echo "No saved self-host config found at $CONFIG_FILE" >&2
    echo "Run: bun run deploy:self-host" >&2
    exit 1
  fi
  # shellcheck disable=SC1090
  . "$CONFIG_FILE"
  cat <<EOF
Client configuration:
  COTERM_API_BASE_URL=${COTERM_API_BASE_URL:-}
  COTERM_COLLABORATION_RELAY_URL=${COTERM_COLLABORATION_RELAY_URL:-}
  COTERM_PRESENCE_BASE_URL=${COTERM_PRESENCE_BASE_URL:-}

Auth mode:
  COLLAB_AUTH_MODE=${COLLAB_AUTH_MODE:-}

Saved config:
  $CONFIG_FILE

Agent context:
  bun run context:self-host -- --format markdown

Configure a DEBUG client:
  bun run configure:client -- --guest-id <name>
EOF
}

replace_toml_string() {
  local file="$1"
  local key="$2"
  local value="$3"
  local escaped="${value//\\/\\\\}"
  escaped="${escaped//\"/\\\"}"

  if ! grep -Eq "^${key}[[:space:]]*=" "$file"; then
    echo "Missing ${key} in ${file}" >&2
    exit 1
  fi

  perl -0pi -e "s#^${key}\\s*=\\s*\"[^\"]*\"#${key} = \"${escaped}\"#m" "$file"
}

deploy_worker() {
  local worker_dir="$1"
  local service_name="$2"
  local tmp
  tmp="$(mktemp)"

  echo >&2
  echo "==> Deploying ${service_name}" >&2
  set +e
  (cd "$ROOT/$worker_dir" && bunx wrangler deploy) 2>&1 | tee "$tmp" >&2
  local status="${PIPESTATUS[0]}"
  set -e
  if [ "$status" -ne 0 ]; then
    rm -f "$tmp"
    echo "Deploy failed: ${service_name}" >&2
    exit "$status"
  fi

  local url
  url="$(sed -nE 's#.*(https://[^[:space:]]+\.workers\.dev).*#\1#p' "$tmp" | tail -n 1)"
  rm -f "$tmp"
  if [ -z "$url" ]; then
    echo "Could not find the workers.dev URL for ${service_name} in wrangler output." >&2
    echo "If you deploy only to a custom domain, set the URL manually in the client." >&2
    exit 1
  fi

  printf '%s\n' "$url"
}

health_check() {
  local url="$1"
  local service="$2"
  echo "==> Checking ${service}: ${url}/healthz"
  curl -fsS "${url}/healthz" >/dev/null
}

put_secret() {
  local worker_dir="$1"
  local name="$2"
  local value="$3"
  printf '%s' "$value" | (cd "$ROOT/$worker_dir" && bunx wrangler secret put "$name")
}

write_config_file() {
  cat >"$CONFIG_FILE" <<EOF
# Generated by scripts/deploy-self-host.sh.
# Safe to paste into the Coterm client settings. Does not contain secrets.
COTERM_API_BASE_URL=$CONTROL_URL
COTERM_COLLABORATION_RELAY_URL=$RELAY_URL
COTERM_PRESENCE_BASE_URL=$PRESENCE_URL
COLLAB_AUTH_MODE=$AUTH_MODE
EOF
}

write_context_file() {
  if bun scripts/self-host-context.ts --config "$CONFIG_FILE" --format json --write "$CONTEXT_FILE" >/dev/null; then
    echo "==> Wrote self-host agent context: $CONTEXT_FILE"
  else
    echo "WARN could not write self-host agent context." >&2
  fi
}

if [ "$PRINT_CONFIG" = "1" ]; then
  print_saved_config
  exit 0
fi

need_command bun
need_command curl
need_command grep
need_command perl
need_command openssl

cd "$ROOT"

if [ ! -d "$ROOT/node_modules" ]; then
  echo "==> Installing dependencies"
  bun install
fi

if ! bunx wrangler whoami >/dev/null 2>&1; then
  echo "==> Opening Cloudflare login"
  bunx wrangler login
fi

replace_toml_string "$ROOT/workers/relay/wrangler.toml" "COLLAB_AUTH_MODE" "$AUTH_MODE"
replace_toml_string "$ROOT/workers/control-plane/wrangler.toml" "COLLAB_AUTH_MODE" "$AUTH_MODE"
replace_toml_string "$ROOT/workers/presence/wrangler.toml" "COLLAB_AUTH_MODE" "$AUTH_MODE"

RELAY_URL="$(deploy_worker "workers/relay" "coterm-relay")"
replace_toml_string "$ROOT/workers/control-plane/wrangler.toml" "COLLAB_RELAY_URL" "$RELAY_URL"
CONTROL_URL="$(deploy_worker "workers/control-plane" "coterm-control-plane")"
PRESENCE_URL="$(deploy_worker "workers/presence" "coterm-presence")"

if [ "$AUTH_MODE" = "hmac" ]; then
  GENERATED_SECRET="$(openssl rand -hex 32)"
  echo
  echo "==> Installing shared COLLAB_AUTH_SECRET on all workers"
  put_secret "workers/relay" "COLLAB_AUTH_SECRET" "$GENERATED_SECRET"
  put_secret "workers/control-plane" "COLLAB_AUTH_SECRET" "$GENERATED_SECRET"
  put_secret "workers/presence" "COLLAB_AUTH_SECRET" "$GENERATED_SECRET"
fi

echo
health_check "$RELAY_URL" "relay"
health_check "$CONTROL_URL" "control-plane"
health_check "$PRESENCE_URL" "presence"

write_config_file
write_context_file

if [ "$RUN_SMOKE" = "1" ]; then
  echo
  echo "==> Running live e2e smoke test"
  if [ "$AUTH_MODE" = "hmac" ]; then
    COLLAB_AUTH_MODE="$AUTH_MODE" \
    COLLAB_AUTH_SECRET="$GENERATED_SECRET" \
    COTERM_COLLAB_CONTROL_URL="$CONTROL_URL" \
    COTERM_COLLABORATION_RELAY_URL="$RELAY_URL" \
    bun scripts/smoke-e2e.ts
  else
    COLLAB_AUTH_MODE="$AUTH_MODE" \
    COTERM_COLLAB_CONTROL_URL="$CONTROL_URL" \
    COTERM_COLLABORATION_RELAY_URL="$RELAY_URL" \
    bun scripts/smoke-e2e.ts
  fi
fi

cat <<EOF

Coterm self-host deployment complete.

Client configuration:
  COTERM_API_BASE_URL=$CONTROL_URL
  COTERM_COLLABORATION_RELAY_URL=$RELAY_URL
  COTERM_PRESENCE_BASE_URL=$PRESENCE_URL

Auth mode:
  COLLAB_AUTH_MODE=$AUTH_MODE

Local files updated:
  $CONFIG_FILE contains the client configuration above.
  $CONTEXT_FILE contains non-secret context for Coterm and coding agents.
  workers/control-plane/wrangler.toml now points COLLAB_RELAY_URL at your relay.
  All worker wrangler.toml files use COLLAB_AUTH_MODE=$AUTH_MODE.

Next:
  bun run configure:client -- --guest-id <name>
  bun run doctor:self-host
EOF
